[package]
name = "a01_savedb_rocksdb"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
surrealdb = { version = "2.6.1", features = ["kv-rocksdb"] }
tokio = { version = "1.49.0", features = ["full"] }
