[package]
name = "a01_csv_savedb_rocksdb"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
surrealdb = { version = "2.6.1", features = ["kv-rocksdb"] }
